### PR TITLE
Dynamic Stream Supervisor

### PR DESCRIPTION
**Pull request by thekeele**

### CODE REVIEW

**Comment by rcehemann** [comment]
I'm able to add and remove streams but I get the following message when trying to list them:
image

**Comment by thekeele** [comment]
Hmm I'm not able to reproduce that one. `Registry.select/2` is an elixir module function, it should be included. Try this in `iex`
```
👉  h Registry.select/2

                           def select(registry, spec)

  @spec select(registry(), spec()) :: [term()]

since: 1.9.0
```
Are you on elixir 1.9.0 or greater?

**Comment by rcehemann** [comment]
> Are you on elixir 1.9.0 or greater?
I was not. updated to 1.9.1 and it's working fine

**Comment by thekeele** [comment]
Excellent, I updated the mix file to indicate that bitfeels requires elixir 1.9 or greater.

**Pull request merged**
